spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ems
    username: root
    password: kalyan
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        #demo
        #demooo